import Head from 'next/head'
import Layout from '@/components/layout'

export default function Projects() {
  return (
    <>
      <Layout>
        <Head>
          <title>Jaehyeok's Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>프로젝트</h1>
      </Layout>
    </>
  )
}
